name: Publish packages to GitHub Packages

on:
  workflow_dispatch:

permissions:
  contents: write
  packages: write

jobs:
  publish-knex-legacy-v1:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: '0.12'

      - run: npm install
        env:
          NPM_PACKAGE_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - run: npm publish
        working-directory: ./knex-legacy-jqv1
        env:
          NPM_PACKAGE_TOKEN: ${{ secrets.GITHUB_TOKEN }}
